name: 'Preview PR'

on: 
  workflow_dispatch:
  pull_request:
    branches:    
      - developer
    types: [opened]
    
permissions: 
  write-all
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: get pull request ref
          id: get_pull_request_ref
          uses: octokit/request-action@v2.x
          with:
            route: GET /repos/:repository/pulls/:issue_id
            repository: ${{ github.repository }}
            issue_id: ${{ github.event.issue.number }}
          env:
            GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  
        - name: create deployment
          id: create_deployment
          uses: octokit/request-action@v2.x
          with:
            route: POST /repos/:repository/deployments
            repository: ${{ github.repository }}
            ref: ${{ fromJson(steps.get_pull_request_ref.outputs.data).head.ref }}
            environment:  ${{ env.TAG_NAME }}
            environment_url: ${{ env.PREVIEW_URL }}
            auto_merge: false
          env:
            GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    
    